api_taurus_info:
    pattern:  /taurus/index
    defaults: { _controller: ApiTaurusBundle:Default:index }
    requirements:
        _format: json
    
api_taurus_verify_secret_code:
    pattern:  /taurus/verify/secret-code
    defaults: { _controller: ApiTaurusBundle:Default:verifySecretCode }
    requirements:
        _format: json
    
api_taurus_verify_authorization_code:
    pattern:  /taurus/verify/authorization-code
    defaults: { _controller: ApiTaurusBundle:Default:veryfyAuthorizationCode }
    requirements:
        _format: json
    
api_taurus_execute_payment:
    pattern:  /taurus/execute/transaction
    defaults: { _controller: ApiTaurusBundle:Default:executeTransaction }
    requirements:
        _format: json
